ALTER TABLE usuarios
ADD COLUMN IF NOT EXISTS proveedor_auth VARCHAR(20) NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS codigo_recuperacion VARCHAR(6) NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS codigo_expiracion DATETIME NULL DEFAULT NULL;
